services:
  - type: web
    name: trail-equip
    runtime: docker
    plan: free
    region: ohio
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: SPRING_JPA_DATABASE_PLATFORM
        value: org.hibernate.dialect.PostgreSQL10Dialect
      - key: SPRING_APPLICATION_NAME
        value: trail-equip
      - fromGroup: trail-equip-db

databases:
  - name: trail-equip-db
    plan: free
    region: ohio
    databaseName: trailequip
    user: trailequip_user
