services:
  - type: web
    name: trail-equip
    runtime: docker
    plan: free
    region: ohio
    healthCheckPath: /actuator/health
    healthCheckInterval: 60
    dockerfile: ./Dockerfile
    dockerContext: .
    port: 8080
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:5432/${DB_NAME}
      - key: SPRING_DATASOURCE_USERNAME
        value: ${DB_USER}
      - key: SPRING_DATASOURCE_PASSWORD
        value: ${DB_PASSWORD}
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: SPRING_JPA_DATABASE_PLATFORM
        value: org.hibernate.dialect.PostgreSQL10Dialect
      - key: SPRING_APPLICATION_NAME
        value: trail-equip-service
      - key: PORT
        value: "8080"

databases:
  - name: trail-equip-db
    databaseName: trailequip
    user: trailequip_user
    plan: free
    region: ohio
    postgresMajorVersion: "15"
